#!/usr/bin/env bash
# =============================================================================
# coder-install-brave.sh — Install Brave browser for smoke testing (persistent).
#
#   bash deploy/coder-install-brave.sh
#
# On Ubuntu ≥ 24.04 the t64 ABI transition renamed many libraries
# (libatk1.0-0 → libatk1.0-0t64 etc.), so Brave's official .deb dependencies
# no longer resolve. Instead of apt-installing the package (which would also
# land in the ephemeral image layer), this script:
#
#   1. Downloads the official Brave .deb (cached in /opt/coder/sonos-tt/downloads)
#   2. Installs the runtime libraries via apt (t64-aware name resolution)
#   3. Extracts Brave's payload to /opt/coder/sonos-tt/tools/brave (persistent!)
#   4. Creates a `brave-browser` wrapper in /usr/local/bin
#
# A Coder workspace update may wipe /usr/local/bin and apt packages — re-run
# this script to restore (the .deb comes from the persistent cache, no
# re-download needed).
# =============================================================================
set -euo pipefail

PERSIST_ROOT="/opt/coder/sonos-tt"
DOWNLOADS_DIR="$PERSIST_ROOT/downloads"
TOOLS_DIR="$PERSIST_ROOT/tools"
BRAVE_DIR="$TOOLS_DIR/brave"          # extraction root (persistent)
DEB="$DOWNLOADS_DIR/brave-browser-latest.deb"

log() { printf '\n[brave] %s\n' "$*"; }

# ─── Runtime libraries Brave needs (pre-t64 names; resolved to t64 below) ───
LIB_DEPS="ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 \
libatk1.0-0 libatspi2.0-0 libc6 libcairo2 libcups2 libcurl3-gnutls \
libdbus-1-3 libexpat1 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 \
libpango-1.0-0 libudev1 libvulkan1 libx11-6 libxcb1 libxcomposite1 \
libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils"

# True if the package has an installable candidate (virtual packages don't).
# NOTE: must NOT use `grep -q` in a pipe here — grep -q exits on first match,
# apt-cache gets SIGPIPE, and `set -o pipefail` turns that into a false result.
has_candidate() {
    local n
    n="$(apt-cache policy "$1" 2>/dev/null | grep -c 'Candidate: [^()]' || true)"
    [ "$n" -gt 0 ]
}

resolve_and_install_libs() {
    local pkgs=() p
    for p in $LIB_DEPS; do
        if has_candidate "$p"; then
            pkgs+=("$p")
        elif has_candidate "${p}t64"; then
            pkgs+=("${p}t64")          # t64 ABI-renamed package
        else
            echo "[brave] WARN: neither $p nor ${p}t64 installable — skipping" >&2
        fi
    done
    log "installing runtime libraries: ${pkgs[*]}"
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${pkgs[@]}"
}

download_deb() {
    if [ -f "$DEB" ]; then
        log "using cached .deb: $DEB"
        return 0
    fi
    log "downloading latest Brave .deb from GitHub releases…"
    local url
    url="$(curl -fsSL https://api.github.com/repos/brave/brave-browser/releases/latest \
        | grep -o 'https://github.com/[^"]*brave-browser[^"]*amd64\.deb' | head -1)"
    [ -n "$url" ] || { echo "No .deb asset found in latest release" >&2; return 1; }
    curl -fSL --retry 3 "$url" -o "$DEB"
}

install_persistent_extract() {
    if [ ! -x "$BRAVE_DIR/root/opt/brave.com/brave/brave" ]; then
        download_deb
        mkdir -p "$BRAVE_DIR"
        log "extracting .deb → $BRAVE_DIR/root"
        dpkg-deb -x "$DEB" "$BRAVE_DIR/root"
    else
        log "persistent Brave payload already present at $BRAVE_DIR"
    fi
    resolve_and_install_libs

    # .deb payloads extract with restrictive modes/ownership — make them
    # usable by the workspace user and ensure the persistent area stays theirs.
    chmod -R a+rX "$BRAVE_DIR/root"
    if [ "$(id -u)" -eq 0 ]; then
        chown -R coder:coder "$PERSIST_ROOT" 2>/dev/null || true
    fi

    # Wrapper script (recreated on every run — cheap and survives image resets)
    local wrapper=/usr/local/bin/brave-browser
    cat > "$wrapper" <<EOF
#!/bin/bash
# Generated by deploy/coder-install-brave.sh — persistent Brave launcher.
exec /opt/coder/sonos-tt/tools/brave/root/opt/brave.com/brave/brave "\$@"
EOF
    chmod +x "$wrapper"
    # Convenience alias without dash as well
    ln -sf "$wrapper" /usr/local/bin/brave
    log "wrapper installed: $wrapper"
}

# ─── Main ────────────────────────────────────────────────────────────────────
if [ -x /usr/local/bin/brave-browser ] && /usr/local/bin/brave-browser --version >/dev/null 2>&1; then
    log "Brave already working: $(/usr/local/bin/brave-browser --version 2>/dev/null || echo '?')"
    exit 0
fi

install_persistent_extract

log "verifying…"
brave-browser --version
log "done."